# Generated by Django 5.0.6 on 2024-06-22 18:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Farmer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('pincode', models.CharField(max_length=6)),
                ('aadhar_no', models.CharField(max_length=12)),
                ('contact_no', models.CharField(max_length=10)),
                ('area_ploughed', models.FloatField()),
                ('season', models.CharField(max_length=100)),
                ('crop_grown', models.CharField(max_length=100)),
                ('seeds_used', models.CharField(max_length=100)),
                ('date_of_seed_sown', models.DateField()),
                ('transplanting_method', models.CharField(choices=[('manual', 'Manual'), ('machine', 'Machine')], max_length=50)),
                ('irrigation_method', models.CharField(choices=[('borewell', 'Borewell'), ('drip', 'Drip'), ('well', 'Well'), ('river', 'River'), ('rain', 'Rain')], max_length=50)),
                ('fertilizers_used', models.CharField(choices=[('organic', 'Organic'), ('chemical', 'Chemical'), ('bioinputs', 'Bioinputs')], max_length=50)),
                ('date_of_harvesting', models.DateField()),
                ('yield_kg', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='MediaFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('videofile', models.FileField(upload_to='videos/')),
                ('textquery', models.CharField(max_length=100)),
                ('ngouploadvideo', models.FileField(blank=True, upload_to='ngouploadvideos/')),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.farmer')),
            ],
        ),
    ]
